version: "3.9"

services:

  # Autenticación
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - observabilidad-net

  # Observabilidad - Colector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # gRPC receiver
      - "4318:4318"   # HTTP receiver
      - "8889:8889"   # Prometheus metrics endpoint
    networks:
      - observabilidad-net

  # Observabilidad - Métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - observabilidad-net

  # Observabilidad - Logs
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - observabilidad-net

  # Observabilidad - Visualización
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - observabilidad-net
    depends_on:
      - prometheus
      - loki

  # Base de Datos
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: observabilidad_documental_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - observabilidad-net

  # Backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - observabilidad-net
    depends_on:
      - keycloak
      - otel-collector
      - postgres

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - observabilidad-net
    depends_on:
      - backend

networks:
  observabilidad-net:
    driver: bridge

volumes:
  postgres_data:
  keycloak_data: