"""agregar campos de analisis IA

Revision ID: 30f2135757de
Revises: 66d228b4ae09
Create Date: 2026-08-10 10:24:48.906743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f2135757de'
down_revision: Union[str, None] = '66d228b4ae09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ai_analysis', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ai_analyzed_at')
    op.drop_column('documents', 'ai_analysis')
    # ### end Alembic commands ###
