"""agregar campos de flujo de aprobacion

Revision ID: 66d228b4ae09
Revises: 66049694bc6b
Create Date: 2026-08-03 09:25:58.934470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d228b4ae09'
down_revision: Union[str, None] = '66049694bc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('review_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'review_comment')
    op.drop_column('documents', 'reviewed_at')
    op.drop_column('documents', 'reviewed_by')
    # ### end Alembic commands ###
